/*
@
 This file contains the types constants
@
*/

export const FETCH_UX_CATEGORIES_REQUEST = "FETCH_UX_CATEGORIES_REQUEST ";
export const FETCH_UX_CATEGORIES_FAILURE = "FETCH_UX_CATEGORIES_FAILURE ";
export const FETCH_UX_CATEGORIES_SUCCESS = "FETCH_UX_CATEGORIES_SUCCESS ";
