/*
@
 This file contains the types constants
@
*/

export const POST_INVITATION_REQUEST = "POST_INVITATION_REQUEST ";
export const POST_INVITATION_FAILURE = "POST_INVITATION_FAILURE ";
export const POST_INVITATION_SUCCESS = "POST_INVITATION_SUCCESS ";
