/*
@
 This file contains the types constants
@
*/

export const FETCH_HOSTS_REQUEST = "FETCH_HOSTS_REQUEST ";
export const FETCH_HOSTS_FAILURE = "FETCH_HOSTS_FAILURE ";
export const FETCH_HOSTS_SUCCESS = "FETCH_HOSTS_SUCCESS ";


export const ADD_HOST_VOTE_REQUEST = "ADD_HOST_VOTE_REQUEST ";
export const ADD_HOST_VOTE_FAILURE = "ADD_HOST_VOTE_FAILURE ";
export const ADD_HOST_VOTE_SUCCESS = "ADD_HOST_VOTE_SUCCESS ";

