/*
@
 This file contains the types constants
@
*/

export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST ";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE ";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS ";

export const SEARCH_EVENTS_REQUEST = "SEARCH_EVENTS_REQUEST";
export const SEARCH_EVENTS_SUCCESS = "SEARCH_EVENTS_SUCCESS";
export const SEARCH_EVENTS_ERROR = "SEARCH_EVENTS_ERROR";

export const CLEAR_EVENTS = "CLEAR_EVENTS";
