/*
@
 This file contains the types constants
@
*/

export const FETCH_TALENTS_REQUEST = "FETCH_TALENTS_REQUEST ";
export const FETCH_TALENTS_FAILURE = "FETCH_TALENTS_FAILURE ";
export const FETCH_TALENTS_SUCCESS = "FETCH_TALENTS_SUCCESS ";

export const ADD_TALENT_VOTE_REQUEST = "ADD_TALENT_VOTE_REQUEST ";
export const ADD_TALENT_VOTE_FAILURE = "ADD_TALENT_VOTE_FAILURE ";
export const ADD_TALENT_VOTE_SUCCESS = "ADD_TALENT_VOTE_SUCCESS ";

export const CLEAR_TALENTS = "CLEAR_TALENTS ";

export const SEARCH_TALENTS_REQUEST = "SEARCH_TALENTS_REQUEST";
export const SEARCH_TALENTS_SUCCESS = "SEARCH_TALENTS_SUCCESS";
export const SEARCH_TALENTS_ERROR = "SEARCH_TALENTS_ERROR";
