/*
@
 This file contains the types constants
@
*/

export const FETCH_TALENTS_REQUEST = "FETCH_TALENTS_REQUEST ";
export const FETCH_TALENTS_FAILURE = "FETCH_TALENTS_FAILURE ";
export const FETCH_TALENTS_SUCCESS = "FETCH_TALENTS_SUCCESS ";

export const ADD_TALENT_VOTE_REQUEST = "ADD_TALENT_VOTE_REQUEST ";
export const ADD_TALENT_VOTE_FAILURE = "ADD_TALENT_VOTE_FAILURE ";
export const ADD_TALENT_VOTE_SUCCESS = "ADD_TALENT_VOTE_SUCCESS ";
