/*
@
 This file contains the types constants
@
*/

export const FETCH_HOST_CATEGORIES_REQUEST = "FETCH_HOST_CATEGORIES_REQUEST ";
export const FETCH_HOST_CATEGORIES_FAILURE = "FETCH_HOST_CATEGORIES_FAILURE ";
export const FETCH_HOST_CATEGORIES_SUCCESS = "FETCH_HOST_CATEGORIES_SUCCESS ";
